title: (black ink)
author: bis83
description: Thought is the sculptor who can create the person you want to be.
markdown: kramdown

twitter_username: bis83gb
github_username: bis83

show_excerpts: true

theme: minima

include:
  - _pages

header_pages:
  - _pages/basilico.md
  
gems:
  - jekyll-feed
  - jekyll-seo-tag
